name: Build and Deploy

on:
  push:
    branches:
      - '**'  # This wildcard

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Mask and Print Secrets
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME ${DOCKER_USERNAME}"
          echo "DOCKERHUB_ACCESS_TOKEN: $DOCKERHUB_ACCESS_TOKEN"
          echo "ff $TEST ${TEST}"
          echo "${{ vars.DOCKER_USERNAME }}"
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
          TEST: "ffffdddd"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-repository:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ vars.DROPLET_IP }}
          username: ${{ vars.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose pull
            docker-compose up -d
